remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

# Site settings
title: pySQLY - Python Standard Query Language | SQL with YAML Syntax
tagline: Simplify database interactions across SQLite, MySQL, PostgreSQL, Oracle, MS SQL Server
description: pySQLY is a Python library that standardizes SQL querying with YAML syntax, making database operations consistent across multiple database engines
author: Standard Query Language
lang: en_US
show_downloads: true
url: https://standard-query-language.github.io
baseurl: /pySQLY

# SEO settings

social:
  name: pySQLY
  links:
    - https://github.com/Standard-Query-Language/pySQLY
    - https://pypi.org/project/pysql
    - https://standard-query-language.github.io/pySQLY/
    - https://twitter.com/pySQLY

# Theme customization
colors:
  header: "#2E7BCF"
  gradient_top: "#2E7BCF"
  gradient_bottom: "#2A6DA9"
  link: "#2E7BCF"
  section_headings: "#2E7BCF"

# Navigation
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: API Reference
    url: /api/
  - title: Examples
    url: /examples/
  - title: GitHub
    url: https://github.com/Standard-Query-Language/pySQLY

# Jekyll Minifier settings
jekyll-minifier:
  compress_css: true
  compress_javascript: true
  compress_json: true
  compress_html: true
  exclude: ['*.xml', '*.txt']

# Keywords for SEO
keywords: python, sql, yaml, database, query language, sqlite, mysql, postgresql, oracle, sql server
