remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

# Site settings
title: Python Standard Query Language (pySQLY) Documentation
description: A powerful Python library for standardized SQL querying
show_downloads: true
google_analytics: # Add your GA tracking ID here if needed

# Theme customization
colors:
  header: "#2E7BCF"
  gradient_top: "#2E7BCF"
  gradient_bottom: "#2A6DA9"
  link: "#2E7BCF"
  section_headings: "#2E7BCF"

# Navigation
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Examples
    url: /examples/
  - title: GitHub
    url: https://github.com/Standard-Query-Language/pySQLY
