name: Tag

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
        WITH_V: true
